services:
  catalog1:
    build:
      context: ./catalog_service
      dockerfile: Dockerfile
    container_name: bazar-catalog-service-1
    ports:
      - "5001:5001"
    environment:
      - FRONTEND_URL=http://frontend:5000
      - REPLICA_URL=http://catalog2:5001
    volumes:
      - ./catalog_service/catalog1.db:/app/catalog.db
    networks:
      - bazar-network

  catalog2:
    build:
      context: ./catalog_service
      dockerfile: Dockerfile
    container_name: bazar-catalog-service-2
    ports:
      - "5003:5001"
    environment:
      - FRONTEND_URL=http://frontend:5000
      - REPLICA_URL=http://catalog1:5001

    volumes:
      - ./catalog_service/catalog2.db:/app/catalog.db
    networks:
      - bazar-network

  order1:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: bazar-order-service-1
    ports:
      - "5002:5002"
    environment:
      - CATALOG_URL=http://catalog1:5001
      - ORDER_REPLICA_URL=http://order2:5002

    depends_on:
      - catalog1
      - catalog2
    volumes:
      - ./order_service/orders1.db:/app/orders.db
    networks:
      - bazar-network

  order2:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: bazar-order-service-2
    ports:
      - "5004:5002"
    environment:
      - CATALOG_URL=http://catalog2:5001
      - ORDER_REPLICA_URL=http://order1:5002

    depends_on:
      - catalog1
      - catalog2
    volumes:
      - ./order_service/orders2.db:/app/orders.db
    networks:
      - bazar-network

  frontend:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
    container_name: bazar-frontend-service
    ports:
      - "5000:5000"
    environment:
      - CATALOG_REPLICAS=http://catalog1:5001,http://catalog2:5001
      - ORDER_REPLICAS=http://order1:5002,http://order2:5002
    depends_on:
      - catalog1
      - catalog2
      - order1
      - order2
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge