
services:
  catalog:
    build:
      context: ./catalog_service
      dockerfile: Dockerfile
    container_name: bazar-catalog-service
    ports:
      - "5001:5001"
    networks:
      - bazar-network

  order:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: bazar-order-service
    ports:
      - "5002:5002"
    environment:
      - CATALOG_URL=http://catalog:5001
    depends_on:
      - catalog
    networks:
      - bazar-network

  frontend:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
    container_name: bazar-frontend-service
    ports:
      - "5000:5000"
    environment:
      - CATALOG_URL=http://catalog:5001
      - ORDER_URL=http://order:5002
    depends_on:
      - catalog
      - order
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge